/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.bean.Material;
import model.bean.MaterialTabela;
import model.bean.Produto;
import model.dao.MaterialDAO;
import model.dao.ProdutoDAO;

/**
 *
 * @author Usuário
 */
public class GerenciaBOM extends javax.swing.JFrame {

    DefaultListModel dlm = new DefaultListModel();
    MaterialTabela model = new MaterialTabela();

    List<Produto> listProd;
    List<Material> listMat;

    /**
     * Creates new form GerenciaBOM
     */
    public GerenciaBOM() {
        initComponents();

//        lblErroNomeProd.setVisible(false);
//        lblErroNomeMat.setVisible(false);
//        lblErroQuantMat.setVisible(false);
        carregarListaProdCompleta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProdutos = new javax.swing.JList<>();
        btAtualizaProduto = new javax.swing.JButton();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btAddProduto = new javax.swing.JButton();
        lblErroNomeProd = new javax.swing.JLabel();
        btEditarProd = new javax.swing.JButton();
        btExcluirProd = new javax.swing.JButton();
        txtBuscaProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMateriais = new javax.swing.JTable();
        btAtualizaMaterial = new javax.swing.JButton();
        txtBuscaMate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodMaterial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeMate = new javax.swing.JTextField();
        txtQuantMaterial = new javax.swing.JTextField();
        lblErroNomeMat = new javax.swing.JLabel();
        btAddMat = new javax.swing.JButton();
        btExcluirMat = new javax.swing.JButton();
        btEditarMat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar B.O.M.");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));

        listProdutos.setModel(dlm);
        listProdutos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProdutos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listProdutosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listProdutos);

        btAtualizaProduto.setText("Atualizar Produtos");
        btAtualizaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAtualizaProdutoMouseClicked(evt);
            }
        });

        txtNomeProduto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNomeProdutoCaretUpdate(evt);
            }
        });

        jLabel1.setText("Nome:");

        btAddProduto.setText("Adicionar");
        btAddProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddProdutoMouseClicked(evt);
            }
        });

        lblErroNomeProd.setForeground(new java.awt.Color(255, 0, 0));
        lblErroNomeProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErroNomeProd.setText("* Nome obrigatório");
        lblErroNomeProd.setVisible(false);

        btEditarProd.setText("Editar");
        btEditarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEditarProdMouseClicked(evt);
            }
        });

        btExcluirProd.setText("Excluir");
        btExcluirProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirProdMouseClicked(evt);
            }
        });

        txtBuscaProd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscaProdCaretUpdate(evt);
            }
        });

        jLabel5.setText("Buscar: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btAddProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btExcluirProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btAtualizaProduto))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscaProd))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeProduto))
            .addComponent(lblErroNomeProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAddProduto, btEditarProd, btExcluirProd});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btAtualizaProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErroNomeProd)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddProduto)
                    .addComponent(btEditarProd)
                    .addComponent(btExcluirProd)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAddProduto, btEditarProd, btExcluirProd});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Materiais"));

        tableMateriais.setAutoCreateRowSorter(true);
        tableMateriais.setModel(model);
        tableMateriais.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableMateriais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMateriaisMouseClicked(evt);
            }
        });
        tableMateriais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableMateriaisKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableMateriais);

        btAtualizaMaterial.setText("Atualizar Materiais");
        btAtualizaMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAtualizaMaterialMouseClicked(evt);
            }
        });

        jLabel2.setText("Código: ");

        jLabel3.setText("Nome: ");

        jLabel4.setText("Quantidade:");

        lblErroNomeMat.setForeground(new java.awt.Color(255, 0, 0));
        lblErroNomeMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErroNomeMat.setText("* Nome obrigatório");
        lblErroNomeMat.setVisible(false);

        btAddMat.setText("Adicionar");
        btAddMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddMatMouseClicked(evt);
            }
        });

        btExcluirMat.setText("Excluir");
        btExcluirMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMatMouseClicked(evt);
            }
        });

        btEditarMat.setText("Editar");
        btEditarMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEditarMatMouseClicked(evt);
            }
        });

        jLabel6.setText("Buscar: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btAddMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btEditarMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btExcluirMat))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCodMaterial)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantMaterial))
                    .addComponent(txtNomeMate)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscaMate))
            .addComponent(lblErroNomeMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btAtualizaMaterial))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAddMat, btEditarMat, btExcluirMat});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btAtualizaMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErroNomeMat)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddMat)
                    .addComponent(btExcluirMat)
                    .addComponent(btEditarMat)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAddMat, btEditarMat, btExcluirMat});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAtualizaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtualizaProdutoMouseClicked
        carregarListaProdCompleta();
        txtBuscaProd.setText("");
    }//GEN-LAST:event_btAtualizaProdutoMouseClicked

    private void txtNomeProdutoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNomeProdutoCaretUpdate
        lblErroNomeProd.setVisible(false);
    }//GEN-LAST:event_txtNomeProdutoCaretUpdate

    private void btAddProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddProdutoMouseClicked
        // TODO add your handling code here:
        String nome = txtNomeProduto.getText();
        if (nome.trim().equals("")) {
            lblErroNomeProd.setVisible(true);
        } else {
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();

            p.setNome(nome);
            dao.create(p);
            carregarListaProdCompleta();
        }
    }//GEN-LAST:event_btAddProdutoMouseClicked

    private void listProdutosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProdutosValueChanged
        txtNomeProduto.setText(listProdutos.getSelectedValue());
        int index = listProdutos.getSelectedIndex();
        carregarListaMatCompleta(listProd.get(index).getId());
    }//GEN-LAST:event_listProdutosValueChanged

    private void btEditarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditarProdMouseClicked
        int index = listProdutos.getSelectedIndex();

        if (index != -1) {
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();

            p.setId(listProd.get(index).getId());
            p.setNome(txtNomeProduto.getText());

            dao.update(p);
            carregarListaProdCompleta();
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado!");
        }

    }//GEN-LAST:event_btEditarProdMouseClicked

    private void btExcluirProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirProdMouseClicked
        int index = listProdutos.getSelectedIndex();

        if (index != -1) {
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();

            p.setId(listProd.get(index).getId());

            dao.delete(p);
            carregarListaProdCompleta();
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado!");
        }
    }//GEN-LAST:event_btExcluirProdMouseClicked

    private void txtBuscaProdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscaProdCaretUpdate
        // TODO add your handling code here:
        ProdutoDAO dao = new ProdutoDAO();

        listProd.clear();
        listProd = dao.search(txtBuscaProd.getText());

        carregarListaProdBusca(txtBuscaProd.getText());
    }//GEN-LAST:event_txtBuscaProdCaretUpdate

    private void btAddMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddMatMouseClicked
        int index = listProdutos.getSelectedIndex();
        
        if (index != -1) {
            String cod = txtCodMaterial.getText();
            String nome = txtNomeMate.getText();
            String quant = txtQuantMaterial.getText();

            if (nome.trim().equals("")) {
                lblErroNomeMat.setVisible(true);
                lblErroNomeMat.setText("* Nome obrigatório");
            } else if (quant.trim().equals("")) {
                lblErroNomeMat.setVisible(true);
                lblErroNomeMat.setText("* Quantidade obrigatória");
            } else {                
                Material m = new Material();
                
                m.setId_produto(listProd.get(index).getId());
                m.setCod(Integer.parseInt(cod));
                m.setNome(nome);
                m.setQuant(Integer.parseInt(quant));

                MaterialDAO dao = new MaterialDAO();
                dao.create(m);
                carregarListaMatCompleta(listProd.get(index).getId());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado!");
        }

    }//GEN-LAST:event_btAddMatMouseClicked

    private void btAtualizaMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtualizaMaterialMouseClicked
        int index = listProdutos.getSelectedIndex();

        if (index != -1) {
            carregarListaMatCompleta(listProd.get(index).getId());
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado!");
        }
    }//GEN-LAST:event_btAtualizaMaterialMouseClicked

    private void tableMateriaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableMateriaisKeyReleased
        int index = tableMateriais.getSelectedRow();
        
        if(index != -1){
            String cod = tableMateriais.getValueAt(index, 0).toString();
            String nome = tableMateriais.getValueAt(index, 1).toString();
            String quant = tableMateriais.getValueAt(index, 2).toString();
                        
            txtCodMaterial.setText(cod);
            txtNomeMate.setText(nome);
            txtQuantMaterial.setText(quant);
        }
    
    }//GEN-LAST:event_tableMateriaisKeyReleased

    private void tableMateriaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMateriaisMouseClicked
        int index = tableMateriais.getSelectedRow();
        
        if(index != -1){
            String cod = tableMateriais.getValueAt(index, 0).toString();
            String nome = tableMateriais.getValueAt(index, 1).toString();
            String quant = tableMateriais.getValueAt(index, 2).toString();
                        
            txtCodMaterial.setText(cod);
            txtNomeMate.setText(nome);
            txtQuantMaterial.setText(quant);
        }
    }//GEN-LAST:event_tableMateriaisMouseClicked

    private void btEditarMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEditarMatMouseClicked
        int index = tableMateriais.getSelectedRow();
        int idProd = listProdutos.getSelectedIndex();

        if (index != -1) {
            Material m = new Material();
            MaterialDAO dao = new MaterialDAO();

            m.setId(listMat.get(index).getId());
            m.setNome(txtNomeMate.getText());
            m.setCod(Long.parseLong(txtCodMaterial.getText()));
            m.setQuant(Integer.parseInt(txtQuantMaterial.getText()));

            dao.update(m);
            carregarListaMatCompleta(listProd.get(idProd).getId());
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum Material selecionado!");
        }
    }//GEN-LAST:event_btEditarMatMouseClicked

    private void btExcluirMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMatMouseClicked
        int index = tableMateriais.getSelectedRow();
        int idProd = listProdutos.getSelectedIndex();

        if (index != -1) {
            Material m = new Material();
            MaterialDAO dao = new MaterialDAO();

            m.setId(listMat.get(index).getId());

            dao.delete(m);
            carregarListaMatCompleta(listProd.get(idProd).getId());
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado!");
        }
    }//GEN-LAST:event_btExcluirMatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaBOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaBOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaBOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaBOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GerenciaBOM().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddMat;
    private javax.swing.JButton btAddProduto;
    private javax.swing.JButton btAtualizaMaterial;
    private javax.swing.JButton btAtualizaProduto;
    private javax.swing.JButton btEditarMat;
    private javax.swing.JButton btEditarProd;
    private javax.swing.JButton btExcluirMat;
    private javax.swing.JButton btExcluirProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErroNomeMat;
    private javax.swing.JLabel lblErroNomeProd;
    private javax.swing.JList<String> listProdutos;
    private javax.swing.JTable tableMateriais;
    private javax.swing.JTextField txtBuscaMate;
    private javax.swing.JTextField txtBuscaProd;
    private javax.swing.JTextField txtCodMaterial;
    private javax.swing.JTextField txtNomeMate;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtQuantMaterial;
    // End of variables declaration//GEN-END:variables

    private void carregarListaProdCompleta() {
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> prod = dao.read();
        atualizarProdutos(prod);
    }

    private void carregarListaProdBusca(String nome) {
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> prod = dao.search(nome);
        atualizarProdutos(prod);
    }

    private void atualizarProdutos(List<Produto> prod) {
        ProdutoDAO dao = new ProdutoDAO();
        listProd = prod;

        dlm = (DefaultListModel) listProdutos.getModel();

        dlm.clear();
        for (int i = 0; i < listProd.size(); i++) {
            dlm.add(i, listProd.get(i).getNome());
        }
    }

    private void carregarListaMatBusca(String nome) {
        MaterialDAO dao = new MaterialDAO();
        List<Material> mat = dao.search(nome);
        atualizarMateriais(mat);
    }

    private void carregarListaMatCompleta(int index) {
        MaterialDAO dao = new MaterialDAO();
        List<Material> mat = dao.read(index);
        atualizarMateriais(mat);
    }

    private void atualizarMateriais(List<Material> mat) {
        MaterialDAO dao = new MaterialDAO();
        listMat = mat;
        model = new MaterialTabela(listMat);

        tableMateriais.setModel(model);
    }
}
